### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by marijneken**
I'm not sure if the URL I changed is the correct one, but the old URL doesn't exist.

### CODE REVIEW

**Comment by caseda** [comment]
It is not recommended to use this module anyway but the [mesh driver](https://github.com/athombv/node-homey-meshdriver), especially for new apps, as this module is SDKv1 based, and new apps are not allowed anymore with SDKv1.

**Comment by marijneken** [comment]
As I'm just getting my feet wet in Homey App development, I wouldn't have guessed that the Mesh Driver is superseding this one. Maybe it would be helpful to mention that in the docs and point to the Mesh Driver?

**Comment by caseda** [comment]
The developer documentation already only point to the mesh driver. 
I guess you just started at the module, instead of at the documentation itself (which is the right starting point), probably because of other apps that are still using SDKv1

**Comment by WeeJeWel** [comment]
Thanks! I've also updated the README with a deprecation warning.

**Pull request merged**
